from .auth import auth_router
from .cves import cves_router
from .cwes import cwes_router
from .assessments import assessments_router
from .deployment_scenario import deployment_scenarios_router
from .asset import assets_router
from .system_profile import system_profile_router
from .cpe import cpe_router
from .helper import helper_router
from .countermeasure import countermeasure_router
from .risk_assessment import risk_assessment_router
from .risk_monitoring import risk_monitoring_router
from .admin import admin_router