version: '3.8'

networks:
  default:

services:
  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: always
    entrypoint: sh
    command:
      - -c
      - envsubst '$${DOCUMENT_ROOT}' < /etc/nginx/conf.d/default.conf.tpl | tee /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"
    environment:
      - DOCUMENT_ROOT=${NGINX_DOCUMENT_ROOT:-/web/public}
      - DOMAIN=${DOMAIN:-localhost}
    volumes:
      - ${NGINX_CONFIG_PASSWORD:-./config/nginx/.htpasswd}:/etc/nginx/.htpasswd
      - ${NGINX_CONFIG_TEMPLATE:-./config/nginx/default.conf}:/etc/nginx/conf.d/default.conf.tpl:ro
    ports:
      - ${PORT:-80}:80
    networks:
      default:
    logging:
      driver: none

  react:
    image: node:14.17.6-alpine
    # command: yarn start
    volumes:
      - ${WEB_PATH}:/web
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_react
    tty: true
    working_dir: /web
    networks:
      default:
